name: frontend
replicaCount: 2

deployment:
  name: frontend-deploy

image:
  name: frontend-api
  repository: __replace__
  tag: __replace__
  pullPolicy: Always

probes:
  liveness:
    port: 80
    endpoint: /swagger/index.html
  readiness:
    port: 80
    endpoint: /swagger/index.html

container:
  port: 80

resources: 
  requests:
   cpu: 100m
   memory: 128Mi
  limits:
   cpu: 500m
   memory: 256Mi

env:
  backendurl: __replace__
  appinsightskey: __replace__

service:
  name: frontend-svc
  type: ClusterIP
  port: 80
  targetport: 80

ingress:
  name: frontend-ingress
  host: __replace__