name: backend
replicaCount: 2

deployment:
  name: backend-deploy

image:
  name: backend-api
  repository: __replace__
  tag: __replace__
  pullPolicy: Always

probes:
  liveness:
    port: 80
    endpoint: /swagger/index.html
  readiness:
    port: 80
    endpoint: /swagger/index.html

container:
  port: 80

resources: 
  requests:
   cpu: 100m
   memory: 128Mi
  limits:
   cpu: 500m
   memory: 256Mi

env:
  mongoconnectionstring: __replace__
  mongodatabase: __replace__
  mongocollection: __replace__
  appinsightskey: __replace__

service:
  name: backend-svc
  type: ClusterIP
  port: 8080
  targetport: 80