# Default values for backend-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: backend
replicaCount: 2

deployment:
  name: backend

image:
  name: backend-api
  repository: aksworkshopregistry.azurecr.io/aksworkshop/backend-api
  tag: 1
  pullPolicy: Always

probes:
  liveness:
    port: 80
    endpoint: /swagger/index.html
  readiness:
    port: 80
    endpoint: /swagger/index.html

container:
  port: 80

service:
  type: LoadBalancer
  port: 80
  name: backend

resources: 
  requests:
   cpu: 100m
   memory: 128Mi
  limits:
   cpu: 500m
   memory: 256Mi

mongo:
  connectionstring: mongodb://user:Passw0rd!@todolist-mongo-mongodb.default.svc.cluster.local:27017/
  database: todoitems
  collection: todolist

appinsights:
  key: b1e8f3c6-bd36-47bb-8de9-221b9848f78f
